language: python

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
    - sudo rm /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

jobs:  
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: ./unit-tests
      install: 
        - docker-compose -f ./docker-compose.test.yml -p ci build
        - docker-compose -f ./docker-compose.test.yml -p ci up -d
      script:
        - docker logs -f ci_web_1
        - docker wait ci_web_1
      after-script: docker-compose -p ci down
      name: "Dev Docker Build"  
      install: docker-compose build
      script: docker-compose up -d --build

script:
    - docker-compose up -d --build
